/**
 * Create Test Orders Script
 *
 * This script creates 100 test orders in Shopify for the revoatest store.
 * Used to test subscription blocking logic based on order count limits.
 *
 * Usage:
 *   npx tsx scripts/create-test-orders.ts
 */

import { createClient } from '@supabase/supabase-js';

// Supabase configuration
const SUPABASE_URL = process.env.SUPABASE_URL || process.env.VITE_SUPABASE_URL || '';
const SUPABASE_SERVICE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY || '';

// Shopify API version
const SHOPIFY_API_VERSION = '2025-07';

// Number of test orders to create
const NUM_ORDERS = 60;

// Rate limiting delay (milliseconds)
const DELAY_BETWEEN_REQUESTS = 500;

interface ShopifyStore {
  id: string;
  store_url: string;
  access_token: string;
}

interface ProductVariant {
  id: string;
  price: string;
  title: string;
}

interface Product {
  id: string;
  title: string;
  variants: { edges: Array<{ node: ProductVariant }> };
}

/**
 * Sleep helper for rate limiting
 */
const sleep = (ms: number) => new Promise(resolve => setTimeout(resolve, ms));

/**
 * Generate random order amount between min and max
 */
const randomAmount = (min: number, max: number): string => {
  return (Math.random() * (max - min) + min).toFixed(2);
};

/**
 * Generate random customer name
 */
const randomCustomerName = (index: number): { firstName: string; lastName: string } => {
  const firstNames = ['John', 'Jane', 'Michael', 'Sarah', 'David', 'Emily', 'Chris', 'Jessica', 'Daniel', 'Ashley'];
  const lastNames = ['Smith', 'Johnson', 'Williams', 'Brown', 'Jones', 'Garcia', 'Miller', 'Davis', 'Rodriguez', 'Martinez'];

  return {
    firstName: firstNames[index % firstNames.length],
    lastName: lastNames[Math.floor(index / firstNames.length) % lastNames.length]
  };
};

/**
 * Execute Shopify GraphQL query
 */
async function shopifyGraphQL<T>(
  shop: string,
  accessToken: string,
  query: string,
  variables?: Record<string, any>
): Promise<T> {
  const url = `https://${shop}/admin/api/${SHOPIFY_API_VERSION}/graphql.json`;

  const response = await fetch(url, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'X-Shopify-Access-Token': accessToken,
    },
    body: JSON.stringify({ query, variables }),
  });

  if (!response.ok) {
    throw new Error(`Shopify GraphQL HTTP error: ${response.status} ${response.statusText}`);
  }

  const result = await response.json();

  if (result.errors && result.errors.length > 0) {
    throw new Error(`GraphQL errors: ${result.errors.map((e: any) => e.message).join(', ')}`);
  }

  return result.data;
}

/**
 * Fetch products from Shopify store
 */
async function getProducts(shop: string, accessToken: string): Promise<Product[]> {
  const query = `
    query GetProducts($first: Int!) {
      products(first: $first) {
        edges {
          node {
            id
            title
            variants(first: 1) {
              edges {
                node {
                  id
                  title
                  price
                }
              }
            }
          }
        }
      }
    }
  `;

  const data = await shopifyGraphQL<{
    products: { edges: Array<{ node: Product }> };
  }>(shop, accessToken, query, { first: 10 });

  return data.products.edges.map(edge => edge.node);
}

/**
 * Create a draft order
 */
async function createDraftOrder(
  shop: string,
  accessToken: string,
  variantId: string,
  price: string,
  customerName: { firstName: string; lastName: string },
  orderIndex: number
): Promise<string> {
  const mutation = `
    mutation draftOrderCreate($input: DraftOrderInput!) {
      draftOrderCreate(input: $input) {
        draftOrder {
          id
          name
        }
        userErrors {
          field
          message
        }
      }
    }
  `;

  const input = {
    lineItems: [
      {
        variantId: variantId,
        quantity: 1,
      }
    ],
    note: `Test order #${orderIndex + 1} - Generated by test script`,
    email: `test-customer-${orderIndex + 1}@example.com`,
    taxExempt: false,
    useCustomerDefaultAddress: false,
    billingAddress: {
      firstName: customerName.firstName,
      lastName: customerName.lastName,
      address1: `${123 + orderIndex} Test St`,
      city: 'Test City',
      province: 'CA',
      zip: '90210',
      country: 'US',
      phone: '+1-555-0100'
    },
    shippingAddress: {
      firstName: customerName.firstName,
      lastName: customerName.lastName,
      address1: `${123 + orderIndex} Test St`,
      city: 'Test City',
      province: 'CA',
      zip: '90210',
      country: 'US',
      phone: '+1-555-0100'
    }
  };

  const data = await shopifyGraphQL<{
    draftOrderCreate: {
      draftOrder: { id: string; name: string };
      userErrors: Array<{ field: string; message: string }>;
    };
  }>(shop, accessToken, mutation, { input });

  if (data.draftOrderCreate.userErrors.length > 0) {
    throw new Error(`Draft order creation error: ${data.draftOrderCreate.userErrors[0].message}`);
  }

  return data.draftOrderCreate.draftOrder.id;
}

/**
 * Complete a draft order
 */
async function completeDraftOrder(
  shop: string,
  accessToken: string,
  draftOrderId: string
): Promise<void> {
  const mutation = `
    mutation draftOrderComplete($id: ID!) {
      draftOrderComplete(id: $id) {
        draftOrder {
          id
          order {
            id
            name
          }
        }
        userErrors {
          field
          message
        }
      }
    }
  `;

  const data = await shopifyGraphQL<{
    draftOrderComplete: {
      draftOrder: { id: string; order: { id: string; name: string } };
      userErrors: Array<{ field: string; message: string }>;
    };
  }>(shop, accessToken, mutation, { id: draftOrderId });

  if (data.draftOrderComplete.userErrors.length > 0) {
    throw new Error(`Draft order completion error: ${data.draftOrderComplete.userErrors[0].message}`);
  }
}

/**
 * Main execution
 */
async function main() {
  console.log('=================================');
  console.log('Test Order Creation Script');
  console.log('=================================\n');

  // Validate environment variables
  if (!SUPABASE_URL || !SUPABASE_SERVICE_KEY) {
    console.error('❌ Error: Missing Supabase configuration');
    console.error('   Required: SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY');
    process.exit(1);
  }

  // Initialize Supabase client
  console.log('📦 Initializing Supabase client...');
  const supabase = createClient(SUPABASE_URL, SUPABASE_SERVICE_KEY, {
    auth: {
      autoRefreshToken: false,
      persistSession: false
    }
  });

  // Fetch store credentials
  console.log('🔍 Fetching revoatest store credentials...');
  const { data: store, error: storeError } = await supabase
    .from('shopify_stores')
    .select('id, store_url, access_token')
    .ilike('store_url', '%revoatest%')
    .single();

  if (storeError || !store) {
    console.error('❌ Error: Could not find revoatest store');
    console.error('   Make sure the store exists in the database');
    process.exit(1);
  }

  console.log(`✅ Found store: ${store.store_url}`);

  // Fetch products
  console.log('\n📦 Fetching products from store...');
  const products = await getProducts(store.store_url, store.access_token);

  if (products.length === 0) {
    console.error('❌ Error: No products found in store');
    console.error('   Please create at least one product first');
    process.exit(1);
  }

  const firstProduct = products[0];
  const firstVariant = firstProduct.variants.edges[0]?.node;

  if (!firstVariant) {
    console.error('❌ Error: Product has no variants');
    process.exit(1);
  }

  console.log(`✅ Using product: ${firstProduct.title}`);
  console.log(`   Variant: ${firstVariant.title} ($${firstVariant.price})`);

  // Create test orders
  console.log(`\n🚀 Creating ${NUM_ORDERS} test orders...\n`);

  let successCount = 0;
  let failureCount = 0;
  const startTime = Date.now();

  for (let i = 0; i < NUM_ORDERS; i++) {
    try {
      const customerName = randomCustomerName(i);
      const orderNum = i + 1;

      // Create draft order
      const draftOrderId = await createDraftOrder(
        store.store_url,
        store.access_token,
        firstVariant.id,
        firstVariant.price,
        customerName,
        i
      );

      // Complete draft order
      await completeDraftOrder(store.store_url, store.access_token, draftOrderId);

      successCount++;

      // Log progress every 10 orders
      if (orderNum % 10 === 0) {
        console.log(`✅ Created ${orderNum}/${NUM_ORDERS} orders (${successCount} successful, ${failureCount} failed)`);
      }

      // Rate limiting delay
      if (i < NUM_ORDERS - 1) {
        await sleep(DELAY_BETWEEN_REQUESTS);
      }
    } catch (error) {
      failureCount++;
      console.error(`❌ Failed to create order ${i + 1}:`, error instanceof Error ? error.message : error);
    }
  }

  const endTime = Date.now();
  const duration = ((endTime - startTime) / 1000).toFixed(1);

  // Summary
  console.log('\n=================================');
  console.log('Summary');
  console.log('=================================');
  console.log(`Total orders: ${NUM_ORDERS}`);
  console.log(`✅ Successful: ${successCount}`);
  console.log(`❌ Failed: ${failureCount}`);
  console.log(`⏱️  Duration: ${duration}s`);
  console.log('=================================\n');

  if (failureCount > 0) {
    console.log('⚠️  Some orders failed. Check the errors above.');
    process.exit(1);
  }

  console.log('✅ All test orders created successfully!');
}

// Run the script
main().catch(error => {
  console.error('\n❌ Fatal error:', error);
  process.exit(1);
});
